### ISSUE TITLE
Transparency of typing-notify.hidden not prioritized

### ISSUE THREAD

**Issue by Loctav** [cs96and/FoundryVTT-CGMP#9]
Possibly causing conflicts with other modules that alter the colors in Foundry, elements with the class `typing-notify.hidden` may still display despite receiving the `color: transparent;` attribute. Adding `!important` would fix this issue. This might also happen with modules that alter the height of elements, so maybe priorizing the `max-height` attribute similiarly may help assuring that the element stays hidden under any circumstance.

```CSS
.typing-notify.hidden {
    max-height: 0px;
    color: transparent;
}
```

to

```CSS
.typing-notify.hidden {
    max-height: 0px;
    color: transparent !important;
}
```
